image: Visual Studio 2017 Preview
init:
  - cmd: git config --global core.autocrlf true
branches:
  only:
  - master

install:
- dotnet restore

before_build:


build_script:
- dotnet build

test_script:
- cd PushMate.FcmPushService.Test
- dotnet test --no-build





