image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
branches:
  only:
  - master

install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore --verbosity m
 
before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build



test_script:
- cd PushMate.FcmPushService.Test
- dotnet test
- cd PushMate.TemplatingService.Test
- dotnet test
- cd PushMate.TemplatingService.API.Test
- dotnet test





