image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
branches:
  only:
  - master

install:

before_build:
- dotnet restore --verbosity m

build_script:
- dotnet build

test_script:
- cd PushMate.FcmPushService.Test
- dotnet test
- cd PushMate.TemplatingService.Test
- dotnet test
- cd PushMate.TemplatingService.API.Test
- dotnet test





